FROM node:alpine
ARG TS_VER=latest

RUN corepack enable

WORKDIR /app
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
RUN pnpm install --frozen-lockfile
RUN pnpm add --save-dev typescript@${TS_VER}

COPY tsconfig.json ./
COPY src ./src
COPY test ./test
CMD ["sh", "-c", "/app/node_modules/.bin/tsc --version; pnpm test"]
