FROM node:alpine
ARG TS_VER=latest

WORKDIR /app
COPY package.json package-lock.json ./
RUN npm i -g npm@latest && npm i
RUN npm i --save-dev typescript@${TS_VER}

COPY tsconfig.json ./
COPY src ./src
COPY test ./test
CMD ["sh", "-c", "/app/node_modules/.bin/tsc --version; npm test"]
