import fs from "fs/promises"
import { dirname, join } from "path"
import ts from "typescript"
import { fileURLToPath } from "url"
import { Config, initCtx } from "./config"
import { generateAst, loadSchema } from "./generator"
import { formatCode, printCode } from "./pritner"

export const apigen = async (config: Partial<Config> & Pick<Config, "source" | "output">) => {
  const doc = await loadSchema(config.source)
  const ctx = initCtx({ ...config, doc })
  const { modules, types } = await generateAst(ctx)

  const filepath = join(dirname(fileURLToPath(import.meta.url)), "_template.ts")
  const file = await fs.readFile(filepath, "utf-8")

  let code = [
    `// Auto-generated by https://github.com/vladkens/apigen-ts`,
    `// Source: ${config.source}\n`,
    ...file.split("\n").filter((x) => !x.startsWith("// Note: ")),
  ].join("\n")

  if (!ctx.parseDates) {
    code = code.replace(/PopulateDates.+?\n\s{2}\}/s, "")
    code = code.replace(/this.PopulateDates\((.+)\)/, "$1")
  }

  // broken types by design, but typescript still can print it
  // need to keep original formatting & comments of the template
  code = code.replace("// apigen:modules", printCode(modules as unknown as ts.Statement[]))
  code = code.replace("// apigen:types", printCode(types))
  code = code.replace("class ApiClient", `class ${ctx.name}`)

  await fs.mkdir(dirname(config.output), { recursive: true })
  await fs.writeFile(config.output, await formatCode(code))
}
